### ISSUE TITLE
GLSL 3.30 is not supported.

### ISSUE THREAD

**Issue by fr1tzz** [Drewol/unnamed-sdvx-clone#37] opened 2017-11-25 08:24 UTC
Trying to Get this running under Debian and it seems to fail with an openGL shader error.

Unsure if this is a bug or if I'm missing a dependency but I'm pretty sure this is due to just not having support for the most recent GLSL shader.

If you need me to dump the log file please let me know.

```
[03:15:14][Error] Shader program compile log for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Main: /home/fr1tz/Games/unnamed-sdvx-clone/Shared/include/Shared/Ref.hpp:116: T* Ref<T>::operator->() [with T = Graphics::ShaderRes]: Assertion `IsValid()' failed.
[1]    18283 abort      ./Main
```

**Comment by Drewol** [comment] 2017-11-25 10:00
What kind of hardware are you using?

**Comment by fr1tzz** [comment] 2017-11-25 19:55
I have an AMD 7970 for a GPU and an ivy bridge i5 for a CPU. Anything specific you would like to know? I'm putting a screenfetch in here for a little more info on my machine.


```
         _,met$$$$$gg.           fr1tz@{omitted}
      ,g$$$$$$$$$$$$$$$P.        OS: Debian testing buster
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.13.0-1-amd64
   ,$$P'              `$$$.      Uptime: 15h 49m
  ',$$P       ,ggs.     `$$b:    Packages: 2814
  `d$$'     ,$P"'   .    $$$     Shell: zsh 5.4.2
   $$P      d$'     ,    $$P     Resolution: 5040x1920
   $$:      $$.   -    ,d$$'     WM: i3
   $$\;      Y$b._   _,d$P'      GTK Theme: Beard [GTK3]
   Y$$.    `.`"Y$$$$P"'          CPU: Intel Core i5-3570 @ 4x 4GHz [27.8°C]
   `$$b      "-.__               GPU: AMD TAHITI (DRM 2.50.0 / 4.13.0-1-amd64, LLVM 5.0.0)
    `Y$$                         RAM: 7345MiB / 7944MiB
     `Y$$.                      
       `$$b.                    
         `Y$$b.                 
            `"Y$b._             
                `""""           
                                
fr1tz:~/ $                                                                       [14:50:16]
```

**Comment by Drewol** [comment] 2017-11-25 19:59
hmmm, the 7970 should support opengl 3.3 which is the minimum requirement for unnamed clone. Could be something with your drivers or it wanting to use your intel integrated gpu for some reason.

**Comment by fr1tzz** [comment] 2017-11-25 20:23
Here is a paste of my OpenGL info if that Help
I don't think Debian Testing has drivers out for GLSL 3.3 Is there anyway to have support for older hardware?


```
fr1tz:~/ $ glxinfo | grep OpenGL                                                 [15:18:55]
OpenGL vendor string: X.Org
OpenGL renderer string: AMD TAHITI (DRM 2.50.0 / 4.13.0-1-amd64, LLVM 5.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

```

**Comment by Drewol** [comment] 2017-11-26 18:20
I added some stuff to the game log so that you can see which graphics adapter the game is actually using. Could you try running the game again and then post that?

**Comment by fr1tzz** [comment] 2017-11-26 18:32
Seems like it is attempting to render with my GPU and not the Intel chip.


```
fr1tz:bin/ (master✗) $ ./Main                                                                                                                       [13:15:30]
[13:15:32][Info] Starting task "Application Setup"
[13:15:32][Warning] Failed to open file for reading Main.cfg: 2
[13:15:32][Warning] Failed to load config file
[13:15:33][Info] Listing 2 Joysticks:
[13:15:33][Info] [0] "Microsoft X-Box One pad" (11 buttons, 6 axes, 1 hats)
[13:15:33][Info] [1] "GuitarHero for Playstation (R) 3 GuitarHero for Playstation (R) 3" (13 buttons, 4 axes, 1 hats)
[13:15:33][Info] Starting task "Audio Init"
[13:15:33][Info] Audio driver [0]: pulseaudio
[13:15:33][Info] Audio driver [1]: alsa
[13:15:33][Info] Audio driver [2]: sndio
[13:15:33][Info] Audio driver [3]: dsp
[13:15:33][Info] Audio driver [4]: disk
[13:15:33][Info] Audio driver [5]: dummy
[13:15:33][Info] Using audio driver: pulseaudio
[13:15:33][Info] Audio device [0]: Tahiti HDMI Audio [Radeon HD 7870 XT / 7950/7970] Digital Stereo (HDMI)
[13:15:33][Info] Audio device [1]: Built-in Audio Digital Stereo (IEC958)
[13:15:33][Info] Audio device [2]: USB Modi Device Analog Stereo
[13:15:33][Info] Finished task "Audio Init" in  2 ms
[13:15:33][Info] Starting task "GL Init"
[13:15:33][Info] OpenGL Version: 3.0 Mesa 17.2.5
[13:15:33][Info] OpenGL Shading Language Version: 1.30
[13:15:33][Info] OpenGL Renderer: AMD TAHITI (DRM 2.50.0 / 4.13.0-1-amd64, LLVM 5.0.0)
[13:15:33][Info] OpenGL Vendor: X.Org
[13:15:33][Info] Finished task "GL Init" in  9 ms
[13:15:33][Error] Shader program compile log for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Main: /home/fr1tz/Games/unnamed-sdvx-clone/Shared/include/Shared/Ref.hpp:116: T* Ref<T>::operator->() [with T = Graphics::ShaderRes]: Assertion `IsValid()' failed.
[1]    23616 abort      ./Main

```
Output of logs mentioned above:
```
fr1tz:bin/ (master✗) $ cat /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs                                                   [13:29:22]
#version 330
#extension GL_ARB_separate_shader_objects : enable

layout(location=0) in vec2 inPos;
layout(location=1) in vec2 inTex;

out gl_PerVertex
{
	vec4 gl_Position;
};
layout(location=1) out vec2 fsTex;

uniform mat4 proj;
uniform mat4 world;

void main()
{
	fsTex = inTex;
	gl_Position = proj * world * vec4(inPos.xy, 0, 1);
}

```

**Comment by Drewol** [comment] 2017-11-26 18:48
yeah this definitely seems like a driver issue and I dont really plan on making a version for OpenGL ES as most desktop and laptop hardware from the last 10 years should support OpenGL 3.3

I'm not opposed to someone forking this and making it even more lightweight and make it run on ES though as it would be neat to have something that even a Raspberry Pi could run

**Comment by Dan9er** [comment] 2017-11-27 18:41
I always wanted a *Plug & Play*/*Pandora's Box* style controller... it would be a nice for someone to make a fork of the game that can run on a Pi.

But for now, looks like it's a driver problem on your end. Sorry m8

**Comment by DVN196** [comment] 2017-12-09 18:56
Apparently, the game don't request 3.3 core context so it use your OpenGL version string which is 3.0. My Intel Hd 4000 also have the same problem.

**Comment by Drewol** [comment] 2017-12-09 20:16
I just made it explicitly request an OpenGL 3.3 context in 8c2f7d6f74aa40c0b2da6e90c6635f3e573a02aa this might fix the issues both of you are having.

**Comment by DVN196** [comment] 2017-12-09 21:56
Yeah, it use OpenGl 4.20 now, but it is only a black screen with two white dots. Here is my log:
```
[16:51:06][Info] Starting task "Application Setup"
[16:51:07][Warning] No joysticks found
[16:51:07][Info] Starting task "Audio Init"
[16:51:07][Info] Audio driver [0]: pulseaudio
[16:51:07][Info] Audio driver [1]: alsa
[16:51:07][Info] Audio driver [2]: dsp
[16:51:07][Info] Audio driver [3]: disk
[16:51:07][Info] Audio driver [4]: dummy
[16:51:07][Info] Using audio driver: pulseaudio
[16:51:07][Info] Audio device [0]: Built-in Audio Digital Stereo (HDMI 2)
[16:51:07][Info] Finished task "Audio Init" in  11 ms
[16:51:07][Info] Starting task "GL Init"
[16:51:07][Info] OpenGL Version: 4.2 (Core Profile) Mesa 17.2.6
[16:51:07][Info] OpenGL Shading Language Version: 4.20
[16:51:07][Info] OpenGL Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
[16:51:07][Info] OpenGL Vendor: Intel Open Source Technology Center
[16:51:07][Info] Finished task "GL Init" in  10 ms
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[16:51:07][Info] Uniform [1, loc=1, Unknown [35676]] = world
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/font.fs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[16:51:07][Info] Uniform [1, loc=1, Unknown [35666]] = color
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.vs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[16:51:07][Info] Uniform [1, loc=1, Unknown [35676]] = world
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.fs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[16:51:07][Info] Uniform [1, loc=1, Unknown [35666]] = color
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.vs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[16:51:07][Info] Uniform [1, loc=1, Unknown [35676]] = world
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.fs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35666]] = color
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.vs
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.fs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[16:51:07][Info] Uniform [1, loc=1, Unknown [35666]] = color
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.gs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[16:51:07][Info] Uniform [1, loc=1, Unknown [35676]] = world
[16:51:07][Info] Uniform [2, loc=2, Unknown [35664]] = size
[16:51:07][Info] Uniform [3, loc=3, Unknown [35666]] = border
[16:51:07][Info] Uniform [4, loc=4, Unknown [35666]] = texBorder
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.vs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[16:51:07][Info] Uniform [1, loc=1, Unknown [35676]] = world
[16:51:07][Info] Listing shader uniforms for /home/dvn196/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.fs
[16:51:07][Info] Uniform [0, loc=0, Unknown [35678]] = graphTex
[16:51:07][Info] Uniform [1, loc=1, Unknown [35667]] = viewport
[16:51:07][Info] Finished task "Application Setup" in  222 ms
[16:51:12][Info] Starting task "Application Cleanup"
[16:51:12][Info] Cleaned up 6 resource(s) of N8Graphics7MeshResE
[16:51:12][Info] Cleaned up 13 resource(s) of N8Graphics10TextureResE
[16:51:12][Info] Cleaned up 11 resource(s) of N8Graphics9ShaderResE
[16:51:12][Info] Cleaned up 1 resource(s) of N8Graphics7FontResE
[16:51:12][Info] Cleaned up 5 resource(s) of N8Graphics11MaterialResE
[16:51:13][Info] Finished task "Application Cleanup" in  974 ms

up 5 resource(s) of N8Graphics11MaterialResE
[16:47:34][Info] Finished task "Application Cleanup" in  1675 ms
```

**Comment by nermolov** [comment] 2018-01-05 02:07
Having the same issue on Arch. Just running without providing a song file shows only a black screen, running with a song file shows a glitched song progress indicator in the corner and nothing else.

`glxinfo | grep OpenGL`:
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.3.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.3.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

`neofetch`:
```
                   -`                    nik@arch-spectre
                  .o+`                   ----------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: HP Spectre x360 Convertible
               `+oooooo:                 Kernel: 4.14.10-1-ARCH
               -+oooooo+:                Uptime: 1 day, 10 hours, 1 min
             `/:-:++oooo+:               Packages: 499
            `/++++/+++++++:              Shell: fish 2.7.0
           `/++++++++++++++:             Resolution: 2560x1440
          `/+++ooooooooooooo/`           DE: i3
         ./ooosssso++osssssso+`          Theme: Flat-Plat-Blue-dark-compact [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Papirus [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: urxvt
      :osssssss/        osssso+++.       CPU: Intel i7-6500U (4) @ 3.100GHz
     /ossssssss/        +ssssooo/-       GPU: Intel HD Graphics 520
   `/ossssso+/:-        -:/+osssso+-     Memory: 4044MiB / 15959MiB
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/                           
 .`                                 `/ 
```

Output of running game:
```
[20:06:33][Info] Starting task "Application Setup"
[20:06:33][Warning] No joysticks found
[20:06:33][Info] Starting task "Audio Init"
[20:06:33][Info] Audio driver [0]: pulseaudio
[20:06:33][Info] Audio driver [1]: alsa
[20:06:33][Info] Audio driver [2]: dsp
[20:06:33][Info] Audio driver [3]: disk
[20:06:33][Info] Audio driver [4]: dummy
[20:06:33][Info] Using audio driver: pulseaudio
[20:06:33][Info] Audio device [0]: Built-in Audio Analog Stereo
[20:06:33][Info] Finished task "Audio Init" in  39 ms
[20:06:33][Info] Starting task "GL Init"
[20:06:33][Info] OpenGL Version: 4.5 (Core Profile) Mesa 17.3.1
[20:06:33][Info] OpenGL Shading Language Version: 4.50
[20:06:33][Info] OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
[20:06:33][Info] OpenGL Vendor: Intel Open Source Technology Center
[20:06:33][Info] Finished task "GL Init" in  22 ms
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[20:06:33][Info] Uniform [1, loc=1, Unknown [35676]] = world
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/font.fs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[20:06:33][Info] Uniform [1, loc=1, Unknown [35666]] = color
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.vs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[20:06:33][Info] Uniform [1, loc=1, Unknown [35676]] = world
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.fs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[20:06:33][Info] Uniform [1, loc=1, Unknown [35666]] = color
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.vs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[20:06:33][Info] Uniform [1, loc=1, Unknown [35676]] = world
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.fs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35666]] = color
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.vs
[20:06:33][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.fs
[20:06:33][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[20:06:33][Info] Uniform [1, loc=1, Unknown [35666]] = color
[20:06:34][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.gs
[20:06:34][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[20:06:34][Info] Uniform [1, loc=1, Unknown [35676]] = world
[20:06:34][Info] Uniform [2, loc=2, Unknown [35664]] = size
[20:06:34][Info] Uniform [3, loc=3, Unknown [35666]] = border
[20:06:34][Info] Uniform [4, loc=4, Unknown [35666]] = texBorder
[20:06:34][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.vs
[20:06:34][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[20:06:34][Info] Uniform [1, loc=1, Unknown [35676]] = world
[20:06:34][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.fs
[20:06:34][Info] Uniform [0, loc=0, Unknown [35678]] = graphTex
[20:06:34][Info] Uniform [1, loc=1, Unknown [35667]] = viewport
[20:06:34][Info] Finished task "Application Setup" in  336 ms
[20:06:35][Info] Starting task "Application Cleanup"
[20:06:35][Info] Cleaned up 6 resource(s) of N8Graphics7MeshResE
[20:06:35][Info] Cleaned up 13 resource(s) of N8Graphics10TextureResE
[20:06:35][Info] Cleaned up 11 resource(s) of N8Graphics9ShaderResE
[20:06:35][Info] Cleaned up 1 resource(s) of N8Graphics7FontResE
[20:06:35][Info] Cleaned up 5 resource(s) of N8Graphics11MaterialResE
[20:06:35][Info] Finished task "Application Cleanup" in  62 ms
```

**Comment by Drewol** [comment] 2018-01-05 19:12
@fr1tzz have you tried the game since 8c2f7d6f74aa40c0b2da6e90c6635f3e573a02aa I would like to know if it's been fixed for you since you have a dedicated graphics card while the other two are on Intel HD Graphics

**Comment by nermolov** [comment] 2018-01-07 00:20
bump: doesn't work on my desktop with amd gpu either :/

**Comment by Drewol** [comment] 2018-01-07 01:30
hmmm, are there any alternative drivers for AMD on Linux you can try? I'm not really sure what the issue is and I can't test it myself because my Linux machine has an NVidia GPU and the game runs perfectly fine there.

You can also try building with `_DEBUG` defined and OpenGL might give you some extra info, I think you can do this by adding `set(CMAKE_CXX_FLAGS -D_DEBUG)` to the CMakeLists.txt in the top level directory and re-running `cmake .` and then `make`.

**Comment by fr1tzz** [comment] 2018-01-11 22:22
I have added "set(CMAKE_CXX_FLAGS -D_DEBUG)" to CMakeLists.txt with a fresh copy of the repo and build again with the same results. Here is the debug log as well as a screenshot of the actual game itself when launching.

[Screen Shot](https://i.imgur.com/i4Iv6cZ.png)

`fr1tz:bin/ (master✗) $ ./Main                                                                 [17:16:09]
[17:16:13][Info] Starting task "Application Setup"
[17:16:13][Warning] Failed to open file for reading Main.cfg: 2
[17:16:13][Warning] Failed to load config file
[17:16:13][Info] Listing 1 Joysticks:
[17:16:13][Info] [0] "Microsoft X-Box One pad" (11 buttons, 6 axes, 1 hats)
[17:16:13][Info] Starting task "Audio Init"
[17:16:13][Info] Audio driver [0]: pulseaudio
[17:16:13][Info] Audio driver [1]: alsa
[17:16:13][Info] Audio driver [2]: sndio
[17:16:13][Info] Audio driver [3]: dsp
[17:16:13][Info] Audio driver [4]: disk
[17:16:13][Info] Audio driver [5]: dummy
[17:16:13][Info] Using audio driver: pulseaudio
[17:16:13][Info] Audio device [0]: Tahiti HDMI Audio [Radeon HD 7870 XT / 7950/7970] Digital Stereo (HDMI)
[17:16:13][Info] Audio device [1]: Built-in Audio Digital Stereo (IEC958)
[17:16:13][Info] Audio device [2]: USB Modi Device Analog Stereo
[17:16:13][Info] Finished task "Audio Init" in  4 ms
[17:16:13][Info] Starting task "GL Init"
[17:16:13][Info] OpenGL Version: 4.5 (Core Profile) Mesa 17.2.5
[17:16:13][Info] OpenGL Shading Language Version: 4.50
[17:16:13][Info] OpenGL Renderer: AMD TAHITI (DRM 2.50.0 / 4.14.0-2-amd64, LLVM 5.0.0)
[17:16:13][Info] OpenGL Vendor: X.Org
[17:16:13][Info] Finished task "GL Init" in  6 ms
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[17:16:13][Info] Uniform [1, loc=1, Unknown [35676]] = world
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/font.fs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[17:16:13][Info] Uniform [1, loc=1, Unknown [35666]] = color
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.vs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[17:16:13][Info] Uniform [1, loc=1, Unknown [35676]] = world
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.fs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[17:16:13][Info] Uniform [1, loc=1, Unknown [35666]] = color
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.vs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[17:16:13][Info] Uniform [1, loc=1, Unknown [35676]] = world
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.fs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35666]] = color
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.vs
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.fs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[17:16:13][Info] Uniform [1, loc=1, Unknown [35666]] = color
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.gs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[17:16:13][Info] Uniform [1, loc=1, Unknown [35676]] = world
[17:16:13][Info] Uniform [2, loc=2, Unknown [35664]] = size
[17:16:13][Info] Uniform [3, loc=3, Unknown [35666]] = border
[17:16:13][Info] Uniform [4, loc=4, Unknown [35666]] = texBorder
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.vs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[17:16:13][Info] Uniform [1, loc=1, Unknown [35676]] = world
[17:16:13][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.fs
[17:16:13][Info] Uniform [0, loc=0, Unknown [35678]] = graphTex
[17:16:13][Info] Uniform [1, loc=1, Unknown [35667]] = viewport
[17:16:13][Info] Finished task "Application Setup" in  383 ms
[17:17:49][Error] Failed to compile statement:
SELECT version FROM `Database`
-> no such table: Database
[17:17:50][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/diffFrame.vs
[17:17:50][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[17:17:50][Info] Uniform [1, loc=1, Unknown [35676]] = world
[17:17:50][Info] Listing shader uniforms for /home/fr1tz/Games/unnamed-sdvx-clone/bin/skins/Default/shaders/diffFrame.fs
[17:17:50][Info] Uniform [0, loc=0, Unknown [35678]] = frame
[17:17:50][Info] Uniform [1, loc=1, Unknown [35678]] = jacket
[17:17:50][Info] Uniform [2, loc=2, Unknown [5126]] = time
[17:17:50][Info] Uniform [3, loc=3, Unknown [5126]] = selected
[17:17:50][Warning] Failed to open file for reading audio/menu_click.wav: 2
[17:17:50][Info] Starting task "Map Database - Enumerate Files and Folders"
[17:17:50][Warning] Can't run ScanFiles, "songs" is not a folder
[17:17:50][Info] Finished task "Map Database - Enumerate Files and Folders" in  0 ms
[17:17:50][Info] Starting task "Map Database - Process Removed Files"
[17:17:50][Info] Finished task "Map Database - Process Removed Files" in  0 ms
[17:17:50][Info] Starting task "Map Database - Process New Files"
[17:17:50][Info] Finished task "Map Database - Process New Files" in  0 ms`

**Comment by nermolov** [comment] 2018-03-02 16:55
Just tried compiling with `set(CMAKE_CXX_FLAGS -D_DEBUG)`, output below happened while still showing a black screen. Running 9da9f5233a18528f065d72e5fd3f4914f3c2407d

```
[10:53:11][Info] Starting task "Application Setup"
[10:53:11][Warning] No joysticks found
[10:53:11][Info] Starting task "Audio Init"
[10:53:11][Info] Audio driver [0]: pulseaudio
[10:53:11][Info] Audio driver [1]: alsa
[10:53:11][Info] Audio driver [2]: dsp
[10:53:11][Info] Audio driver [3]: disk
[10:53:11][Info] Audio driver [4]: dummy
[10:53:11][Info] Using audio driver: pulseaudio
[10:53:11][Info] Audio device [0]: Built-in Audio Analog Stereo
[10:53:11][Info] Finished task "Audio Init" in  97 ms
[10:53:11][Info] Starting task "GL Init"
[10:53:11][Info] OpenGL Logging on.
[10:53:11][Info] OpenGL Version: 4.5 (Core Profile) Mesa 17.3.6
[10:53:11][Info] OpenGL Shading Language Version: 4.50
[10:53:11][Info] OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
[10:53:11][Info] OpenGL Vendor: Intel Open Source Technology Center
[10:53:11][Info] Finished task "GL Init" in  35 ms
[10:53:11][Info] Starting task "GUI Init"
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/font.vs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[10:53:11][Info] Uniform [1, loc=1, Unknown [35676]] = world
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/font.fs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[10:53:11][Info] Uniform [1, loc=1, Unknown [35666]] = color
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.vs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[10:53:11][Info] Uniform [1, loc=1, Unknown [35676]] = world
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiTex.fs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[10:53:11][Info] Uniform [1, loc=1, Unknown [35666]] = color
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.vs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[10:53:11][Info] Uniform [1, loc=1, Unknown [35676]] = world
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiColor.fs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35666]] = color
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.vs
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.fs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35678]] = mainTex
[10:53:11][Info] Uniform [1, loc=1, Unknown [35666]] = color
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiButton.gs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[10:53:11][Info] Uniform [1, loc=1, Unknown [35676]] = world
[10:53:11][Info] Uniform [2, loc=2, Unknown [35664]] = size
[10:53:11][Info] Uniform [3, loc=3, Unknown [35666]] = border
[10:53:11][Info] Uniform [4, loc=4, Unknown [35666]] = texBorder
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.vs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35676]] = proj
[10:53:11][Info] Uniform [1, loc=1, Unknown [35676]] = world
[10:53:11][Info] Listing shader uniforms for /home/nik/playground/unnamed-sdvx-clone/bin/skins/Default/shaders/guiGraph.fs
[10:53:11][Info] Uniform [0, loc=0, Unknown [35678]] = graphTex
[10:53:11][Info] Uniform [1, loc=1, Unknown [35667]] = viewport
[10:53:11][Info] Finished task "GUI Init" in  151 ms
[10:53:11][Info] Starting task "Loading common GUI elements"
[10:53:11][Info] Finished task "Loading common GUI elements" in  3 ms
[10:53:11][Info] Finished task "Application Setup" in  400 ms
[10:53:18][Info] Starting task "Application Cleanup"
[10:53:18][Info] Cleaned up 6 resource(s) of N8Graphics7MeshResE
[10:53:18][Info] Cleaned up 13 resource(s) of N8Graphics10TextureResE
[10:53:18][Info] Cleaned up 11 resource(s) of N8Graphics9ShaderResE
[10:53:18][Info] Cleaned up 1 resource(s) of N8Graphics7FontResE
[10:53:18][Info] Cleaned up 5 resource(s) of N8Graphics11MaterialResE
[10:53:18][Info] Finished task "Application Cleanup" in  738 ms
```

**Comment by Drewol** [comment] 2018-03-19 21:56
I may have finally resolved this issue in 062804bbe801cb517e736f313801335963c29208 please try running the game again.

**Comment by nermolov** [comment] 2018-03-21 04:37
Finally runs, thank you so much!

**Comment by Drewol** [comment] 2018-03-22 16:49
@fr1tzz @DVN196 can you guys also check if it's working now and I'll close this.

**Comment by Hinara** [comment] 2019-10-26 10:59
Should be closed

**Closed** 2019-10-26 11:14 UTC
Labels: bug
