### ISSUE TITLE
Can not browse song list with knobs

### ISSUE THREAD

**Issue by okand** [Drewol/unnamed-sdvx-clone#26] opened 2017-10-26 19:03 UTC
Since the lastest update, d80700dc82a54d053bbf2edf0f230f4e36cada9e (possibly introduced further back, I jumped from f3a3937bd5d4cd7775fa2c2751cbd8189b1a080f to there), I'm unable to navigate the song list with the knobs on my controller. It just pretends to be a keyboard and sends the letters q and w or o and p for each knob and direction.

Doesn't work with the keyboard either, I have to use the arrow keys instead.

**Comment by Drewol** [comment] 2017-10-29 22:49
This was probably introduced in f23fdecd6fbc4e10ce434534c2b266bec75573d4 but I would like some more info to try to understand the issue more. Does the controller send repeated button presses or does it hold it while you turn? Have you tried setting the new setting introduced in that commit (`Key_Sensitivity`) to something really high?

**Comment by okand** [comment] 2017-10-29 22:58
It sends repeated presses while turning the know.

Turning `Key_Sensitivity` up made the menu work. 50 felt like a good amount.

**Comment by Drewol** [comment] 2017-10-29 23:05
For how long does each key press from the controller last?

**Comment by okand** [comment] 2017-10-29 23:38
I'm not sure. It's an arduino running the following with no modifications at all: https://github.com/5argon/UnoSDVXCon/blob/master/SDVXCon.ino

Same debounce and spin tolerance as there.

**Comment by Dan9er** [comment] 2017-10-30 00:32
I have a feeling this problem is dependant on the controller used. @okand sounds like they are using a custom rig with an Arduino. We need to check if this issue exists on a SVSE5 and others.

But... turning up the *default* value for `Key_Sensitivity` wouldn't hurt, right?

**Comment by Drewol** [comment] 2017-10-30 00:33
I know what the issue is and the only real solution i see is to have another keyboard laser mode for controllers that send repeated keypresses instead of holding the keys.

**Comment by Drewol** [comment] 2017-10-30 00:38
Dao controllers (SVSE5, SVRE9) work as they use mouse for knobs and Turbochargers work as they act as actual gamepads. I don't know of any "non-custom" controllers that use the repeated keypress knob style.

**Comment by Drewol** [comment] 2017-10-30 20:53
I added another options for keyboard based lasers in cf54ed79d66cbfb77394f9844746cdd5f52e2bc6 which is not a perfect solution to this but i think it might work decently.

**Comment by okand** [comment] 2017-10-31 11:26
I got my controller (mostly) fixed instead: https://github.com/5argon/UnoSDVXCon/pull/3
Still need to tune it and I should probably get better encoders but it holds the key while turning now.

I can still navigate the menus when turning `Key_sensitivity` back to 3 with this code on the controller.

**Comment by Dan9er** [comment] 2017-11-05 14:16
Should I close this as a wontfix? Looks like it may be a problem with your controller. Or should we add support for controllers that mash keys for lasers?

**Comment by Drewol** [comment] 2017-11-05 14:18
K-Shoot does have a mode for that type of controllers but I personally do not know of anyone with a controller that uses that mode.

**Comment by Dan9er** [comment] 2017-11-05 14:28
~Ok, this is a wontfix. If people start demanding for this controller mode to be refined I will reopen this. However, I don't think this is gonna happen anytime soon.~

Ok, looks like @Drewol actually added support in cf54ed79d66cbfb77394f9844746cdd5f52e2bc6 and forgot to close this issue. Still, if anyone has any problems just make a new issue on the topic.

@okand Good luck with 5argon/UnoSDVXCon#3. Hope it gets merged.

**Closed by Dan9er** 2017-11-05 14:28 UTC
Labels: bug, priority-medium
